[env:lilygo-t-display-s3-amoled]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.mcu = esp32s3
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.f_flash = 80000000L
board_build.flash_mode = qio

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -std=gnu++17

build_unflags = -std=gnu++11

lib_extra_dirs = ..

lib_deps =
    lovyan03/LovyanGFX

monitor_speed = 115200
